name: Makefile CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build Module
        # Ensure your Makefile output is in the root directory
        run: make all

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: "*.zip"
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
